/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/01.Walk_on_Water.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/02.Love_in_an_Elevator.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/03.Rag_Doll.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/04.What_It_Takes.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/05.Dude_Looks_Like_a_Lady.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/06.Janies_Got_a_Gun.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/07.Cryin.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/08.Amazing.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/09.Blind_Man.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/10.Deuces_Are_Wild.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/11.The_Other_Side.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/12.Crazy.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/13.Eat_the_Rich.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/14.Angel.flac
/home/p0l1t1c1an/Music/Aerosmith/Big_Ones/15.Livin_on_the_Edge.flac
/home/p0l1t1c1an/Music/Hadestown/01.Road_to_Hell.flac
/home/p0l1t1c1an/Music/Hadestown/02.Any_Way_the_Wind_Blows.flac
/home/p0l1t1c1an/Music/Hadestown/03.Come_Home_With_Me.flac
/home/p0l1t1c1an/Music/Hadestown/04.Wedding_Song.flac
/home/p0l1t1c1an/Music/Hadestown/05.Epic_I.flac
/home/p0l1t1c1an/Music/Hadestown/06.Livin_It_Up_on_Top.flac
/home/p0l1t1c1an/Music/Hadestown/07.All_Ive_Ever_Known_In_spite_of_herself_intro.flac
/home/p0l1t1c1an/Music/Hadestown/08.All_Ive_Ever_Known.flac
/home/p0l1t1c1an/Music/Hadestown/09.Way_Down_Hadestown.flac
/home/p0l1t1c1an/Music/Hadestown/10.A_Gathering_Storm.flac
/home/p0l1t1c1an/Music/Hadestown/11.Epic_II.flac
/home/p0l1t1c1an/Music/Hadestown/12.Chant.flac
/home/p0l1t1c1an/Music/Hadestown/13.Hey_Little_Songbird.flac
/home/p0l1t1c1an/Music/Hadestown/14.When_the_Chips_Are_Down_Songbird_vs_Rattlesnake_intro.flac
/home/p0l1t1c1an/Music/Hadestown/15.When_the_Chips_Are_Down.flac
/home/p0l1t1c1an/Music/Hadestown/16.Gone_Im_Gone.flac
/home/p0l1t1c1an/Music/Hadestown/17.Wait_for_Me_Hey_the_big_artiste_intro.flac
/home/p0l1t1c1an/Music/Hadestown/18.Wait_for_Me.flac
/home/p0l1t1c1an/Music/Hadestown/19.Why_We_Build_the_Wall.flac
/home/p0l1t1c1an/Music/Hadestown/20.Why_We_Build_the_Wall_Behind_closed_doors_outro.flac
/home/p0l1t1c1an/Music/Hadestown/21.Our_Lady_of_the_Underground.flac
/home/p0l1t1c1an/Music/Hadestown/22.Way_Down_Hadestown_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/23.Flowers.flac
/home/p0l1t1c1an/Music/Hadestown/24.Come_Home_With_Me_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/25.Papers_intro.flac
/home/p0l1t1c1an/Music/Hadestown/26.Papers_instrumental.flac
/home/p0l1t1c1an/Music/Hadestown/27.Nothing_Changes.flac
/home/p0l1t1c1an/Music/Hadestown/28.If_Its_True.flac
/home/p0l1t1c1an/Music/Hadestown/29.How_Long.flac
/home/p0l1t1c1an/Music/Hadestown/30.Chant_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/31.Epic_III.flac
/home/p0l1t1c1an/Music/Hadestown/32.Epic_III_intro_instrumental.flac
/home/p0l1t1c1an/Music/Hadestown/33.Promises.flac
/home/p0l1t1c1an/Music/Hadestown/34.Word_to_the_Wise.flac
/home/p0l1t1c1an/Music/Hadestown/35.His_Kiss_the_Riot.flac
/home/p0l1t1c1an/Music/Hadestown/36.Wait_for_Me_intro_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/37.Wait_for_Me_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/38.Doubt_Comes_In.flac
/home/p0l1t1c1an/Music/Hadestown/39.Road_to_Hell_reprise.flac
/home/p0l1t1c1an/Music/Hadestown/40.We_Raise_Our_Cups.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/01.Piano_Man.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/02.Captain_Jack.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/03.The_Entertainer.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/04.Say_Goodbye_to_Hollywood.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/05.New_York_State_of_Mind.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/06.The_Stranger.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/07.Scenes_From_an_Italian_Restaurant.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/08.Just_the_Way_You_Are.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/09.Movin_Out.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/10.Only_the_Good_Die_Young.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/11.Shes_Always_a_Woman.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/12.My_Life.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/13.Big_Shot.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/14.You_May_Be_Right.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/15.Its_Still_Rock_and_Roll_to_Me.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/16.Dont_Ask_Me_Why.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/17.Shes_Got_a_Way.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/18.Pressure.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/19.Allentown.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/20.Goodnight_Saigon.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/21.Tell_Her_About_It.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/22.Uptown_Girl.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/23.The_Longest_Time.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/24.Youre_Only_Human.flac
/home/p0l1t1c1an/Music/Billy_Joel/Greatest_Hits/25.The_Night_Is_Still_Young.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/01.Maybellene.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/02.Thirty_Days.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/03.You_Cant_Catch_Me.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/04.Too_Much_Monkey_Business.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/05.Roll_Over_Beethoven.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/06.Brown_Eyed_Handsome_Man.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/07.Havana_Moon.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/08.School_Day.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/09.Rock_and_Roll_Music.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/10.Oh_Baby_Doll.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/11.Reelin_and_Rockin.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/12.Sweet_Little_Sixteen.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/13.Johnny_B_Goode.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/14.Around_and_Around.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/15.Beautiful_Delilah.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/16.Carol.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/17.Memphis_Tennessee.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/18.Sweet_Little_Rock_n_Roller.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/19.Little_Queenie.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/20.Almost_Grown.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/21.Back_in_the_USA.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/22.Let_It_Rock.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/23.Im_Talking_About_You.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/24.Come_On.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/25.Nadine.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/26.You_Never_Can_Tell.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/27.Promised_Land.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/28.No_Particular_Place_to_Go.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/29.I_Want_to_Be_Your_Driver.flac
/home/p0l1t1c1an/Music/Chuck_Berry/Definitive_Collection/30.My_Ding_a_ling.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/01.Susie_Q.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/02.I_Put_a_Spell_on_You.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/03.Proud_Mary.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/04.Bad_Moon_Rising.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/05.Lodi.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/06.Green_River.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/07.Commotion.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/08.Down_on_the_Corner.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/09.Fortunate_Son.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/10.Travelin_Band.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/11.Wholl_Stop_the_Rain.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/12.Up_Around_the_Bend.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/13.Run_Through_the_Jungle.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/14.Lookin_out_My_Back_Door.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/15.Long_as_I_Can_See_the_Light.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/16.I_Heard_It_Through_the_Grapevine.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/17.Have_You_Ever_Seen_the_Rain.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/18.Hey_Tonight.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/19.Sweet_Hitch‐Hiker.flac
/home/p0l1t1c1an/Music/Creedence_Clearwater_Revival/Chronicle/20.Someday_Never_Comes.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/01.Take_It_Easy.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/02.Witchy_Woman.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/03.Peaceful_Easy_Feeling.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/04.Desperado.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/05.Tequila_Sunrise.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/06.Doolin_Dalton.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/07.Already_Gone.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/08.The_Best_of_My_Love.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/09.James_Dean.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/10.Ol_55.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/11.Midnight_Flyer.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/12.On_the_Border.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/13.Lyin_Eyes.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/14.One_of_These_Nights.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/15.Take_It_to_the_Limit.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/16.After_the_Thrill_Is_Gone.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/17.Hotel_California.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/18.Life_in_the_Fast_Lane.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/19.Wasted_Time.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/20.Victim_of_Love.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/21.The_Last_Resort.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/22.New_Kid_in_Town.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/23.Please_Come_Home_for_Christmas.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/24.Heartache_Tonight.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/25.The_Sad_Cafe.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/26.I_Cant_Tell_You_Why.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/27.The_Long_Run.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/28.In_the_City.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/29.Those_Shoes.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/30.Seven_Bridges_Road.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/31.Love_Will_Keep_Us_Alive.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/32.Get_Over_It.flac
/home/p0l1t1c1an/Music/Eagles/Greatest_Hits/33.Hole_in_the_World.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/01.Shine_a_Little_Love.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/02.Confusion.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/03.Need_Her_Love.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/04.The_Diary_of_Horace_Wimp.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/05.Last_Train_to_London.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/06.Midnight_Blue.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/07.On_the_Run.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/08.Wishing.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/09.Dont_Bring_Me_Down.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/10.On_the_Run_(home_demo).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/11.Second_Time_Around_(home_demo).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Discovery/12.Little_Town_Flirt.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/01.Eldorado_Overture.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/02.Cant_Get_It_Out_of_My_Head.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/03.Boy_Blue.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/04.Laredo_Tornado.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/05.Poor_Boy_(The_Greenwood).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/06.Mister_Kingdom.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/07.Nobodys_Child.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/08.Illusions_in_G_Major.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/09.Eldorado.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/10.Eldorado_Finale.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/11.Eldorado_Instrumental_Medley.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Eldorado/12.Dark_City.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/01.Tightrope.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/02.Telephone_Line.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/03.Rockaria.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/04.Mission_A_World_Record.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/05.So_Fine.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/06.Livin_Thing.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/07.Above_the_Clouds.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/08.Do_Ya.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/09.Shangri-La.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/10.Telephone_Line_different_vocal.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/11.Surrender.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/12.Tightrope_instrumental_early_rough_mix.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/13.Above_the_Clouds_instrumental_rough_mix.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/14.So_Fine_instrumental_early_rough_mix.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/A_New_World_Record/15.Telephone_Line_instrumental.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/01.Fire_on_High.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/02.Waterfall.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/03.Evil_Woman.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/04.Nightrider.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/05.Poker.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/06.Strange_Magic.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/07.Down_Home_Town.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/08.One_Summer_Dream.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/09.Fire_on_High_Intro_(early_alternative_mix).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/10.Evil_Woman_(stripped_down_mix).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/11.Strange_Magic_(US_single_edit).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Face_the_Music/12.Waterfall_(instrumental_mix).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/01.Turn_to_Stone.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/02.Its_Over.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/03.Sweet_Talkin_Woman.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/04.Across_the_Border.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/05.Night_in_the_City.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/06.Starlight.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/07.Jungle.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/08.Believe_Me_Now.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/09.Steppin_Out.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/10.Standin_in_the_Rain.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/11.Big_Wheels.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/12.Summer_and_Lightning.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/13.Mr._Blue_Sky.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/14.Sweet_Is_the_Night.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/15.The_Whale.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/16.Birmingham_Blues.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/17.Wild_West_Hero.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/18.Wild_West_Hero_(alternate_bridge,_home_demo).flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/19.The_Quick_and_the_Daft.flac
/home/p0l1t1c1an/Music/Electric_Light_Orchestra/Out_of_the_Blue/20.Latitude_88_North.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/01.Your_Song.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/02.Daniel.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/03.Honky_Cat.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/04.Goodbye_Yellow_Brick_Road.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/05.Saturday_Nights_Alright_for_Fighting.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/06.Rocket_Man.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/07.Bennie_and_the_Jets.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/08.Candle_in_the_Wind.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/09.Dont_Let_the_Sun_Go_Down_on_Me.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/10.Border_Song.flac
/home/p0l1t1c1an/Music/Elton_John/Greatest_Hits/11.Crocodile_Rock.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/01.Heartbreak_Hotel.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/02.Dont_Be_Cruel.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/03.Hound_Dog.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/04.Love_Me_Tender.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/05.Too_Much.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/06.All_Shook_Up.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/07.(Let_Me_Be_Your)_Teddy_Bear.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/08.Jailhouse_Rock.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/09.Dont.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/10.Hard_Headed_Woman.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/11.One_Night.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/12.(Now_and_Then_Theres)_A_Fool_Such_as_I.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/13.A_Big_Hunk_o_Love.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/14.Stuck_on_You.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/15.Its_Now_or_Never.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/16.Are_You_Lonesome_Tonight.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/17.Wooden_Heart.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/18.Surrender.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/19.(Maries_the_Name)_His_Latest_Flame.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/20.Cant_Help_Falling_in_Love.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/21.Good_Luck_Charm.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/22.Shes_Not_You.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/23.Return_to_Sender.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/24.(Youre_the)_Devil_in_Disguise.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/25.Crying_in_the_Chapel.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/26.In_the_Ghetto.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/27.Suspicious_Minds.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/28.The_Wonder_of_You.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/29.Burning_Love.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/30.Way_Down.flac
/home/p0l1t1c1an/Music/Elvis_Presley/Elv1s/31.A_Little_Less_Conversation_(JXL_radio_edit_remix).flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/01.Monday_Morning.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/02.Dreams.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/03.You_Make_Loving_Fun.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/04.Go_Your_Own_Way.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/05.Rhiannon.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/06.Say_You_Love_Me.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/07.Im_So_Afraid_live_1997.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/08.Silver_Springs.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/09.Over_My_Head.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/10.Never_Going_Back_Again.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/11.Sara.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/12.Love_in_Store.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/13.Tusk.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/14.Landslide.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/15.Songbird.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/16.Big_Love_live_1997.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/17.Storms.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/18.The_Chain.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/19.Dont_Stop.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/20.What_Makes_You_Think_Youre_the_One.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/21.Gypsy.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/22.Second_Hand_News.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/23.Little_Lies.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/24.Think_About_Me.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/25.Go_Insane_live_1997.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/26.Gold_Dust_Woman.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/27.Hold_Me.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/28.Seven_Wonders.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/29.World_Turning.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/30.Everywhere.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/31.Sisters_of_the_Moon.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/32.Family_Man.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/33.As_Long_as_You_Follow.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/34.No_Questions_Asked.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/35.Skies_the_Limit.flac
/home/p0l1t1c1an/Music/Fleetwood_Mac/Best_Of/36.Paper_Doll.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/01.All_My_Life.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/02.Best_of_You.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/03.Everlong.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/04.The_Pretender.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/05.My_Hero.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/06.Learn_to_Fly.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/07.Times_Like_These.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/08.Monkey_Wrench.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/09.Big_Me.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/10.Breakout.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/11.Long_Road_to_Ruin.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/12.This_Is_a_Call.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/13.Skin_and_Bones.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/14.Wheels.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/15.Word_Forward.flac
/home/p0l1t1c1an/Music/Foo_Fighters/Greatest_Hits/16.Everlong_(acoustic).flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/01.All_or_Nothing_at_All.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/02.Ill_Never_Smile_Again.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/03.Saturday_Night.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/04.Nancy_with_the_Laughing_Face.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/05.Ive_Got_the_World_on_a_String.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/06.Young_at_Heart.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/07.In_the_Wee_Small_Hours_of_the_Morning.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/08.Learnin_the_Blues.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/09.Love_and_Marriage.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/10.Ive_Got_You_Under_My_Skin.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/11.Witchcraft.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/12.All_the_Way.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/13.Come_Fly_With_Me.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/14.One_for_My_Baby.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/15.The_Way_You_Look_Tonight.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/16.My_Kind_of_Town.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/17.Fly_Me_to_the_Moon.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/18.It_Was_a_Very_Good_Year.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/19.Strangers_in_the_Night.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/20.Summer_Wind.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/21.Thats_Life.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/22.My_Way.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/23.Theme_From_New_York_New_York.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/24.Put_Your_Dreams_Away.flac
/home/p0l1t1c1an/Music/Frank_Sinatra/Ultimate_Sinatra/25.Just_in_Time.flac
/home/p0l1t1c1an/Music/Jet_Set_Radio/15.Just_Got_Wicked.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/20.Magical_Girl.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/31.Jet_Grind_Radio.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/26.Dragula_Si_Non_Oscillas_Noli_Tintinnare_Mix.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/01.Let_Mom_Sleep.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/02.Humming_the_Bassline.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/03.Thats_Enough.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/04.Everybody_Jump_Around.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/05.Sneakman.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/06.Bout_The_City.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/07.Mischievous_Boy.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/08.Sweet_Soul_Brother.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/09.Rock_It_On.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/10.Yellow_Bream.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/11.Electric_Tooth_Brush.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/12.Funky_Radio.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/13.Moodys_Shuffle.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/14.Grace_and_Glory.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/16.Miller_Ball_Breakers.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/17.On_the_Bowl_A._Fargus_Mix.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/19.Yappie_Feet.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/21.Super_Brothers.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/22.OK_House.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/23.Improvise.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/24.Patrol_Knob.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/25.Slow.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/27.Jet_Set_Medley.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/28.Jet_Set_Station.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/29.Jet_Set_Groove_1.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/30.Jet_Set_Groove_2.ogg
/home/p0l1t1c1an/Music/Jet_Set_Radio/18.Up_Set_Attack_Deavid_Soul.ogg
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/01.Purple_Haze.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/02.Fire.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/03.The_Wind_Cries_Mary.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/04.Hey_Joe.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/05.All_Along_the_Watchtower.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/06.Stone_Free.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/07.Crosstown_Traffic.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/08.Manic_Depression.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/09.Little_Wing.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/10.If_6_Was_9.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/11.Foxy_Lady.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/12.Bold_as_Love.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/13.Castles_Made_of_Sand.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/14.Red_House.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/15.Voodoo_Child.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/16.Freedom.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/17.Night_Bird_Flying.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/18.Angel.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/19.Dolly_Dagger.flac
/home/p0l1t1c1an/Music/Jimi_Hendrix/The_Best_Of/20.Star_Spangled_Banner.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/01.Gettin_Freaky.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/02.Tutorial.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/03.Bopeebo.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/04.Fresh.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/05.Dad_Battle.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/06.Spookeez.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/07.South.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/08.Pico.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/09.Philly_Nice.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/10.Blammed.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/11.Satin_Panties.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/12.High.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/13.M.I.L.F.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/14.Cocoa.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/15.Eggnog.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/16.Game_Over.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/17.Breakfast.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/18.Fresh_Boyfriend_Remix.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/19.Tutorial_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/20.Bopeebo_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/21.Fresh_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/22.Dad_Battle_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/23.Spookeez_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/24.South_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/25.Pico_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/26.Philly_Nice_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/27.Blammed_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/28.Satin_Panties_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/29.High_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/30.M.I.L.F_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/31.Cocoa_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume1/32.Eggnog_Instrumental.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/01.Give_a_Lil_Bit_Back.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/02.Senpai.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/03.Roses.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/04.Thorns.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/05.Ugh.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/06.Guns.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/07.Stress.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/08.Klaskii_Romper.flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/09.Game_Over_(Pixelday).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/10.Senpai_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/11.Roses_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/12.Thorns_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/13.Ugh_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/14.Guns_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/15.Stress_(Instrumental).flac
/home/p0l1t1c1an/Music/Friday_Night_Funkin/volume2/16.Fresh_(Chill_Remix).flac
/home/p0l1t1c1an/Music/Earthbound/045.A_Bad_Dream.mp3
/home/p0l1t1c1an/Music/Earthbound/056.A_Flash_of_Memory.mp3
/home/p0l1t1c1an/Music/Earthbound/017.A_Good_Buddy.mp3
/home/p0l1t1c1an/Music/Earthbound/024.A_Good_Night_s_Rest.mp3
/home/p0l1t1c1an/Music/Earthbound/012.Alien_Invasion.mp3
/home/p0l1t1c1an/Music/Earthbound/031.Ambush!.mp3
/home/p0l1t1c1an/Music/Earthbound/058.Apple_Kid_s_Theme.mp3
/home/p0l1t1c1an/Music/Earthbound/071.Bad_Morning_to_You.mp3
/home/p0l1t1c1an/Music/Earthbound/119.Battle_Against_a_Machine.mp3
/home/p0l1t1c1an/Music/Earthbound/034.Battle_Against_a_Mobile_Opponent.mp3
/home/p0l1t1c1an/Music/Earthbound/032.Battle_Against_a_Weak_Opponent.mp3
/home/p0l1t1c1an/Music/Earthbound/033.Battle_Against_a_Weird_Opponent.mp3
/home/p0l1t1c1an/Music/Earthbound/040.Battle_Against_an_Unsettling_Opponent.mp3
/home/p0l1t1c1an/Music/Earthbound/089.Battle_Against_Belch.mp3
/home/p0l1t1c1an/Music/Earthbound/110.Bazaar.mp3
/home/p0l1t1c1an/Music/Earthbound/151.Because_I_Love_You.mp3
/home/p0l1t1c1an/Music/Earthbound/028.Bed_and_Breakfast.mp3
/home/p0l1t1c1an/Music/Earthbound/088.Belch_s_Factory.mp3
/home/p0l1t1c1an/Music/Earthbound/098.Boris_Cocktail.mp3
/home/p0l1t1c1an/Music/Earthbound/057.Boy_Meets_Girl_(Twoson).mp3
/home/p0l1t1c1an/Music/Earthbound/001.EarthBound_-_Burp.mp3
/home/p0l1t1c1an/Music/Earthbound/026.Buy_Somethin_Will_Ya!.mp3
/home/p0l1t1c1an/Music/Earthbound/162.Buzz-Buzz_s_Demise.mp3
/home/p0l1t1c1an/Music/Earthbound/018.Buzz_Buzz_s_Prophecy.mp3
/home/p0l1t1c1an/Music/Earthbound/079.Caverns_of_Winters.mp3
/home/p0l1t1c1an/Music/Earthbound/006.Choose_a_File.mp3
/home/p0l1t1c1an/Music/Earthbound/041.Dangerous_Caves.mp3
/home/p0l1t1c1an/Music/Earthbound/064.Dead-End_Chaos_Theatre.mp3
/home/p0l1t1c1an/Music/Earthbound/135.Deeper_into_Ness_Subconscious.mp3
/home/p0l1t1c1an/Music/Earthbound/080.Dr_Andonuts_Lab.mp3
/home/p0l1t1c1an/Music/Earthbound/131.Eight_Melodies.mp3
/home/p0l1t1c1an/Music/Earthbound/027.Enjoy_Your_Stay.mp3
/home/p0l1t1c1an/Music/Earthbound/132.Entering_Magicant___.mp3
/home/p0l1t1c1an/Music/Earthbound/084.Escargo_Express_at_Your_Service!.mp3
/home/p0l1t1c1an/Music/Earthbound/161.Evil_Mani_Mani_Statue.mp3
/home/p0l1t1c1an/Music/Earthbound/039.Franky.mp3
/home/p0l1t1c1an/Music/Earthbound/025.Friendly_Neighbors.mp3
/home/p0l1t1c1an/Music/Earthbound/092.Get_on_the_Bus.mp3
/home/p0l1t1c1an/Music/Earthbound/149.Giygas_Disintegrates.mp3
/home/p0l1t1c1an/Music/Earthbound/148.Giygas_is_Fatally_Wounded!.mp3
/home/p0l1t1c1an/Music/Earthbound/147.Giygas_is_Wounded!.mp3
/home/p0l1t1c1an/Music/Earthbound/144.Giygas_Stirs.mp3
/home/p0l1t1c1an/Music/Earthbound/145.Giygas_Intimidation.mp3
/home/p0l1t1c1an/Music/Earthbound/143.Giygas_s_Intro.mp3
/home/p0l1t1c1an/Music/Earthbound/141.Giygas_Lair.mp3
/home/p0l1t1c1an/Music/Earthbound/082.Going_Down!.mp3
/home/p0l1t1c1an/Music/Earthbound/152.Good_Friends_Bad_Friends.mp3
/home/p0l1t1c1an/Music/Earthbound/062.Happy-Happy_is_Blue.mp3
/home/p0l1t1c1an/Music/Earthbound/070.Heartless_Hotel.mp3
/home/p0l1t1c1an/Music/Earthbound/087.Hi_Hi_Hi.mp3
/home/p0l1t1c1an/Music/Earthbound/156.Hidden_Track.mp3
/home/p0l1t1c1an/Music/Earthbound/023.Home_Sweet_Home.mp3
/home/p0l1t1c1an/Music/Earthbound/029.Hospital.mp3
/home/p0l1t1c1an/Music/Earthbound/103.In_Dalaam__There_is_a_Warrior.mp3
/home/p0l1t1c1an/Music/Earthbound/073.In_Winters__There_is_a_Genius.mp3
/home/p0l1t1c1an/Music/Earthbound/114.Inside_the_Dungeon.mp3
/home/p0l1t1c1an/Music/Earthbound/158.Key_Item_Fanfare.mp3
/home/p0l1t1c1an/Music/Earthbound/109.Kraken_of_the_Sea.mp3
/home/p0l1t1c1an/Music/Earthbound/121.Lava_Springs.mp3
/home/p0l1t1c1an/Music/Earthbound/163.Mechanical_Tinkering.mp3
/home/p0l1t1c1an/Music/Earthbound/115.Megaton_Walk.mp3
/home/p0l1t1c1an/Music/Earthbound/099.Moonside_Swing.mp3
/home/p0l1t1c1an/Music/Earthbound/111.Morning_in_the_Desert.mp3
/home/p0l1t1c1an/Music/Earthbound/105.Mu_Training.mp3
/home/p0l1t1c1an/Music/Earthbound/138.Ness_Awakens_from_the_Nightmare.mp3
/home/p0l1t1c1an/Music/Earthbound/059.Ness_Bike.mp3
/home/p0l1t1c1an/Music/Earthbound/008.Now__Let_s_Go!.mp3
/home/p0l1t1c1an/Music/Earthbound/170.OK_Ssuka_.mp3
/home/p0l1t1c1an/Music/Earthbound/043.Oncoming_Boss.mp3
/home/p0l1t1c1an/Music/Earthbound/030.Oncoming_Foe.mp3
/home/p0l1t1c1an/Music/Earthbound/009.One_Fateful_Night___.mp3
/home/p0l1t1c1an/Music/Earthbound/038.Onett_s_Arcade.mp3
/home/p0l1t1c1an/Music/Earthbound/157.Onett_s_Trumpet_Player.mp3
/home/p0l1t1c1an/Music/Earthbound/005.Opening_Credits.mp3
/home/p0l1t1c1an/Music/Earthbound/019.Otherworldly_Foe.mp3
/home/p0l1t1c1an/Music/Earthbound/060.Paula_s_Theme.mp3
/home/p0l1t1c1an/Music/Earthbound/061.Peaceful_Rest_Valley.mp3
/home/p0l1t1c1an/Music/Earthbound/166.Phase_Distorter_Failed.mp3
/home/p0l1t1c1an/Music/Earthbound/164.Phone.mp3
/home/p0l1t1c1an/Music/Earthbound/106.Pink_Cloud_Shrine.mp3
/home/p0l1t1c1an/Music/Earthbound/016.Pokey.mp3
/home/p0l1t1c1an/Music/Earthbound/142.Pokey_Means_Business!.mp3
/home/p0l1t1c1an/Music/Earthbound/014.Pokey_s_at_the_Door.mp3
/home/p0l1t1c1an/Music/Earthbound/020.Pokey_s_House.mp3
/home/p0l1t1c1an/Music/Earthbound/146.Prayer_for_Safety.mp3
/home/p0l1t1c1an/Music/Earthbound/113.Pyramid.mp3
/home/p0l1t1c1an/Music/Earthbound/083.Rough_Landing.mp3
/home/p0l1t1c1an/Music/Earthbound/011.Rude_Awakening.mp3
/home/p0l1t1c1an/Music/Earthbound/067.Runaway_Five_Left_the_Building!.mp3
/home/p0l1t1c1an/Music/Earthbound/068.Runaway_Five_On_the_Move!.mp3
/home/p0l1t1c1an/Music/Earthbound/101.Runaway_Five_to_the_Rescue!.mp3
/home/p0l1t1c1an/Music/Earthbound/065.Runaway_Five-The_Daily_Show.mp3
/home/p0l1t1c1an/Music/Earthbound/066.Runaway_Five_s_Final_Performance.mp3
/home/p0l1t1c1an/Music/Earthbound/107.Sailing_to_Scaraba.mp3
/home/p0l1t1c1an/Music/Earthbound/044.Sanctuary_Guardian.mp3
/home/p0l1t1c1an/Music/Earthbound/042.Sanctuary_Guardian_s_Challenge.mp3
/home/p0l1t1c1an/Music/Earthbound/086.Saturn_Valley_Caverns.mp3
/home/p0l1t1c1an/Music/Earthbound/097.Save_the_Miners!.mp3
/home/p0l1t1c1an/Music/Earthbound/136.Sea_of_Eden.mp3
/home/p0l1t1c1an/Music/Earthbound/153.Smiles_and_Tears.mp3
/home/p0l1t1c1an/Music/Earthbound/074.Snowman_(Snow_Wood_Boarding_House).mp3
/home/p0l1t1c1an/Music/Earthbound/013.Someone_s_Knocking_at_the_Door.mp3
/home/p0l1t1c1an/Music/Earthbound/129.Sound_Stone-Fire_Spring.mp3
/home/p0l1t1c1an/Music/Earthbound/122.Sound_Stone-Giant_Step.mp3
/home/p0l1t1c1an/Music/Earthbound/123.Sound_Stone-Lilliput_Steps.mp3
/home/p0l1t1c1an/Music/Earthbound/128.Sound_Stone-Lumine_Hall.mp3
/home/p0l1t1c1an/Music/Earthbound/126.Sound_Stone-Magnet_Hill.mp3
/home/p0l1t1c1an/Music/Earthbound/124.Sound_Stone-Milky_Well.mp3
/home/p0l1t1c1an/Music/Earthbound/130.Sound_Stone-No_Sounds.mp3
/home/p0l1t1c1an/Music/Earthbound/127.Sound_Stone-Pink_Cloud.mp3
/home/p0l1t1c1an/Music/Earthbound/125.Sound_Stone-Rainy_Circle.mp3
/home/p0l1t1c1an/Music/Earthbound/165.Spacetoneer.mp3
/home/p0l1t1c1an/Music/Earthbound/160.Spell_Learned.mp3
/home/p0l1t1c1an/Music/Earthbound/159.Spooky___.mp3
/home/p0l1t1c1an/Music/Earthbound/102.Summers__Eternal_Tourist_Trap.mp3
/home/p0l1t1c1an/Music/Earthbound/021.Sunrise_&_Onett_Theme.mp3
/home/p0l1t1c1an/Music/Earthbound/093.Super_Dry_Dance.mp3
/home/p0l1t1c1an/Music/Earthbound/167.Teleportation.mp3
/home/p0l1t1c1an/Music/Earthbound/168.Teleportation_End.mp3
/home/p0l1t1c1an/Music/Earthbound/077.Tessie_Has_Been_Sighted!.mp3
/home/p0l1t1c1an/Music/Earthbound/078.Tessie!.mp3
/home/p0l1t1c1an/Music/Earthbound/036.That_Was_Easy!.mp3
/home/p0l1t1c1an/Music/Earthbound/139.The_Cliff_that_Time_Forgot.mp3
/home/p0l1t1c1an/Music/Earthbound/117.The_Deep_Darkness.mp3
/home/p0l1t1c1an/Music/Earthbound/002.The_Evil_Giygas_Attacks!_(Part_1).mp3
/home/p0l1t1c1an/Music/Earthbound/003.The_Evil_Giygas_Attacks!_(Part_2).mp3
/home/p0l1t1c1an/Music/Earthbound/104.The_Floating_Kingdom_of_Dalaam.mp3
/home/p0l1t1c1an/Music/Earthbound/150.The_Heroes_Return.mp3
/home/p0l1t1c1an/Music/Earthbound/134.The_Jolly_Flying_Man.mp3
/home/p0l1t1c1an/Music/Earthbound/120.The_Lost_Underworld.mp3
/home/p0l1t1c1an/Music/Earthbound/094.The_Metropolis_of_Fourside.mp3
/home/p0l1t1c1an/Music/Earthbound/100.The_Monkeys_Maze.mp3
/home/p0l1t1c1an/Music/Earthbound/140.The_Place.mp3
/home/p0l1t1c1an/Music/Earthbound/137.The_Power.mp3
/home/p0l1t1c1an/Music/Earthbound/155.The_Power_(Alternate].mp3
/home/p0l1t1c1an/Music/Earthbound/081.The_Sky_Runner.mp3
/home/p0l1t1c1an/Music/Earthbound/169.The_Stonehenge_Base_Shuts_Down.mp3
/home/p0l1t1c1an/Music/Earthbound/116.The_Submarine.mp3
/home/p0l1t1c1an/Music/Earthbound/118.The_Tendas_Cave.mp3
/home/p0l1t1c1an/Music/Earthbound/112.The_Unforgiving_Desert.mp3
/home/p0l1t1c1an/Music/Earthbound/108.The_Voyage_Continues.mp3
/home/p0l1t1c1an/Music/Earthbound/091.Threed__Free_at_Last.mp3
/home/p0l1t1c1an/Music/Earthbound/069.Threed__Zombie_Central.mp3
/home/p0l1t1c1an/Music/Earthbound/004.Title_Screen.mp3
/home/p0l1t1c1an/Music/Earthbound/095.Topolla_Theatre__Home_to_the_One_&_Only_Venus.mp3
/home/p0l1t1c1an/Music/Earthbound/010.Unidentified_Falling_Object.mp3
/home/p0l1t1c1an/Music/Earthbound/096.Venus_Live!.mp3
/home/p0l1t1c1an/Music/Earthbound/133.Welcome_Home.mp3
/home/p0l1t1c1an/Music/Earthbound/047.Welcome_to_Your_Sanctuary.mp3
/home/p0l1t1c1an/Music/Earthbound/022.What_a_Great_Picture!.mp3
/home/p0l1t1c1an/Music/Earthbound/015.Whoa!.mp3
/home/p0l1t1c1an/Music/Earthbound/072.Whoops!.mp3
/home/p0l1t1c1an/Music/Earthbound/075.Winters_White.mp3
/home/p0l1t1c1an/Music/Earthbound/076.Winters_Wake_Up_Call.mp3
/home/p0l1t1c1an/Music/Earthbound/046.You_Defeated_the_Boss!.mp3
/home/p0l1t1c1an/Music/Earthbound/037.You_Gained_a_Level!.mp3
/home/p0l1t1c1an/Music/Earthbound/035.You_Win!.mp3
/home/p0l1t1c1an/Music/Earthbound/090.You_ve_Come_Far__Ness.mp3
/home/p0l1t1c1an/Music/Earthbound/063.You_ve_Got_a_New_Friend!.mp3
/home/p0l1t1c1an/Music/Earthbound/007.Your_Name__Please.mp3
/home/p0l1t1c1an/Music/Earthbound/154.Your_Name__Please_(Noiseless).mp3
/home/p0l1t1c1an/Music/Earthbound/055.Your_Sanctuary-Fire_Spring.mp3
/home/p0l1t1c1an/Music/Earthbound/048.Your_Sanctuary-Giant_Step.mp3
/home/p0l1t1c1an/Music/Earthbound/049.Your_Sanctuary-Lilliput_Steps.mp3
/home/p0l1t1c1an/Music/Earthbound/054.Your_Sanctuary-Lumine_Hall.mp3
/home/p0l1t1c1an/Music/Earthbound/052.Your_Sanctuary-Magnet_Hill.mp3
/home/p0l1t1c1an/Music/Earthbound/050.Your_Sanctuary-Milky_Well.mp3
/home/p0l1t1c1an/Music/Earthbound/053.Your_Sanctuary-Pink_Cloud.mp3
/home/p0l1t1c1an/Music/Earthbound/051.Your_Sanctuary-Rainy_Circle.mp3
/home/p0l1t1c1an/Music/Earthbound/085.Zombie_Paper.mp3
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/01.Good_Times_Bad_Times.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/02.Communication_Breakdown.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/03.Dazed_and_Confused.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/04.Babe_Im_Gonna_Leave_You.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/05.Whole_Lotta_Love.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/06.Ramble_On.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/07.Heartbreaker.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/08.Immigrant_Song.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/09.Since_Ive_Been_Loving_You.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/10.Rock_and_Roll.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/11.Black_Dog.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/12.When_the_Levee_Breaks.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/13.Stairway_to_Heaven.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/14.The_Song_Remains_the_Same.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/15.Over_the_Hills_and_Far_Away.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/16.Dyer_Maker.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/17.No_Quarter.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/18.Trampled_Under_Foot.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/19.Houses_of_the_Holy.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/20.Kashmir.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/21.Nobodys_Fault_but_Mine.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/22.Achilles_Last_Stand.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/23.In_the_Evening.flac
/home/p0l1t1c1an/Music/Led_Zeppelin/Mothership/24.All_My_Love.flac
/home/p0l1t1c1an/Music/Hamilton/01.Alexander_Hamilton.flac
/home/p0l1t1c1an/Music/Hamilton/02.Aaron_Burr_Sir.flac
/home/p0l1t1c1an/Music/Hamilton/03.My_Shot.flac
/home/p0l1t1c1an/Music/Hamilton/04.The_Story_of_Tonight.flac
/home/p0l1t1c1an/Music/Hamilton/05.The_Schuyler_Sisters.flac
/home/p0l1t1c1an/Music/Hamilton/06.Farmer_Refuted.flac
/home/p0l1t1c1an/Music/Hamilton/07.Youll_Be_Back.flac
/home/p0l1t1c1an/Music/Hamilton/08.Right_Hand_Man.flac
/home/p0l1t1c1an/Music/Hamilton/09.A_Winters_Ball.flac
/home/p0l1t1c1an/Music/Hamilton/10.Helpless.flac
/home/p0l1t1c1an/Music/Hamilton/11.Satisfied.flac
/home/p0l1t1c1an/Music/Hamilton/12.The_Story_of_Tonight_reprise.flac
/home/p0l1t1c1an/Music/Hamilton/13.Wait_for_It.flac
/home/p0l1t1c1an/Music/Hamilton/14.Stay_Alive.flac
/home/p0l1t1c1an/Music/Hamilton/15.Ten_Duel_Commandments.flac
/home/p0l1t1c1an/Music/Hamilton/16.Meet_Me_Inside.flac
/home/p0l1t1c1an/Music/Hamilton/17.That_Would_Be_Enough.flac
/home/p0l1t1c1an/Music/Hamilton/18.Guns_and_Ships.flac
/home/p0l1t1c1an/Music/Hamilton/19.History_Has_Its_Eyes_on_You.flac
/home/p0l1t1c1an/Music/Hamilton/20.Yorktown_The_World_Turned_Upside_Down.flac
/home/p0l1t1c1an/Music/Hamilton/21.What_Comes_Next.flac
/home/p0l1t1c1an/Music/Hamilton/22.Dear_Theodosia.flac
/home/p0l1t1c1an/Music/Hamilton/23.Non_Stop.flac
/home/p0l1t1c1an/Music/Hamilton/24.Whatd_I_Miss.flac
/home/p0l1t1c1an/Music/Hamilton/25.Cabinet_Battle_1.flac
/home/p0l1t1c1an/Music/Hamilton/26.Take_a_Break.flac
/home/p0l1t1c1an/Music/Hamilton/27.Say_No_to_This.flac
/home/p0l1t1c1an/Music/Hamilton/28.The_Room_Where_It_Happens.flac
/home/p0l1t1c1an/Music/Hamilton/29.Schuyler_Defeated.flac
/home/p0l1t1c1an/Music/Hamilton/30.Cabinet_Battle_2.flac
/home/p0l1t1c1an/Music/Hamilton/31.Washington_on_Your_Side.flac
/home/p0l1t1c1an/Music/Hamilton/32.One_Last_Time.flac
/home/p0l1t1c1an/Music/Hamilton/33.I_Know_Him.flac
/home/p0l1t1c1an/Music/Hamilton/34.The_Adams_Administration.flac
/home/p0l1t1c1an/Music/Hamilton/35.We_Know.flac
/home/p0l1t1c1an/Music/Hamilton/36.Hurricane.flac
/home/p0l1t1c1an/Music/Hamilton/37.The_Reynolds_Pamphlet.flac
/home/p0l1t1c1an/Music/Hamilton/38.Burn.flac
/home/p0l1t1c1an/Music/Hamilton/39.Blow_Us_All_Away.flac
/home/p0l1t1c1an/Music/Hamilton/40.Stay_Alive_reprise.flac
/home/p0l1t1c1an/Music/Hamilton/41.Its_Quiet_Uptown.flac
/home/p0l1t1c1an/Music/Hamilton/42.The_Election_of_1800.flac
/home/p0l1t1c1an/Music/Hamilton/43.Your_Obedient_Servant.flac
/home/p0l1t1c1an/Music/Hamilton/44.Best_of_Wives_and_Best_of_Women.flac
/home/p0l1t1c1an/Music/Hamilton/45.The_World_Was_Wide_Enough.flac
/home/p0l1t1c1an/Music/Hamilton/46.Who_Lives_Who_Dies_Who_Tells_Your_Story.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/01.Join_the_Band.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/02.Fat_Man_in_the_Bathtub.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/03.All_That_You_Dream.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/04.Oh_Atlanta.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/05.Old_Folks_Boogie.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/06.Time_Loves_a_Hero.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/07.Day_or_Night.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/08.Mercenary_Territory.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/09.Spanish_Moon.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/10.Dixie_Chicken.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/11.Tripe_Face_Boogie.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/12.Rocket_in_My_Pocket.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/13.Willin.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/14.Sailin_Shoes.flac
/home/p0l1t1c1an/Music/Little_Feat/Waiting_for_Columbus/15.Feats_Dont_Fail_Me_Now.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/01.Speak_to_Me.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/02.Breathe_in_the_Air.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/03.On_the_Run.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/04.Time.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/05.The_Great_Gig_in_the_Sky.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/06.Money.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/07.Us_and_Them.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/08.Any_Colour_You_Like.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/09.Brain_Damage.flac
/home/p0l1t1c1an/Music/Pink_Floyd/Dark_Side_of_the_Moon/10.Eclipse.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/01.Bohemian_Rhapsody.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/02.Another_One_Bites_the_Dust.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/03.Killer_Queen.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/04.Fat_Bottomed_Girls.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/05.Bicycle_Race.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/06.Youre_My_Best_Friend.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/07.Dont_Stop_Me_Now.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/08.Save_Me.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/09.Crazy_Little_Thing_Called_Love.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/10.Somebody_to_Love.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/11.Now_Im_Here.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/12.Good_Old_Fashioned_Lover_Boy.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/13.Play_the_Game.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/14.Flash.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/15.Seven_Seas_of_Rhye.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/16.We_Will_Rock_You.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits/17.We_Are_the_Champions.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/01.A_Kind_of_Magic.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/02.Under_Pressure.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/03.Radio_Ga_Ga.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/04.I_Want_It_All.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/05.I_Want_to_Break_Free.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/06.Innuendo.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/07.Its_a_Hard_Life.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/08.Breakthru.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/09.Who_Wants_to_Live_Forever.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/10.Headlong.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/11.The_Miracle.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/12.Im_Going_Slightly_Mad.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/13.The_Invisible_Man.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/14.Hammer_to_Fall.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/15.Friends_Will_Be_Friends.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/16.The_Show_Must_Go_On.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_II/17.One_Vision.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/01.The_Show_Must_Go_On.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/02.Under_Pressure_Rah_mix.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/03.Barcelona.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/04.Too_Much_Love_Will_Kill_You.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/05.Somebody_to_Love.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/06.You_Dont_Fool_Me.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/07.Heaven_for_Everyone.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/08.Las_Palabras_de_Amor_The_Words_of_Love.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/09.Driven_by_You.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/10.Living_on_My_Own_Julian_Raymond_mix.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/11.Let_Me_Live.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/12.The_Great_Pretender.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/13.Princes_of_the_Universe.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/14.Another_One_Bites_the_Dust.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/15.No-One_but_You_Only_the_Good_Die_Young.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/16.These_Are_the_Days_of_Our_Lives.flac
/home/p0l1t1c1an/Music/Queen/Greatest_Hits_III/17.Thank_God_Its_Christmas.flac
/home/p0l1t1c1an/Music/Persona_4/01.Pursing_My_Trueself.flac
/home/p0l1t1c1an/Music/Persona_4/02.Glimpse_of_a_Memory.flac
/home/p0l1t1c1an/Music/Persona_4/03.Welcome_to_the_limousine.flac
/home/p0l1t1c1an/Music/Persona_4/04.Aria_of_the_Soul.flac
/home/p0l1t1c1an/Music/Persona_4/05.New_Days.flac
/home/p0l1t1c1an/Music/Persona_4/06.Signs_Of_Love.flac
/home/p0l1t1c1an/Music/Persona_4/07.Midnight_Channel.flac
/home/p0l1t1c1an/Music/Persona_4/08.Your_Affection.flac
/home/p0l1t1c1an/Music/Persona_4/09.Like_a_dream_come_true.flac
/home/p0l1t1c1an/Music/Persona_4/10.Who's_There.flac
/home/p0l1t1c1an/Music/Persona_4/11.Reach_Out_To_The_Truth_-First_Battle-.flac
/home/p0l1t1c1an/Music/Persona_4/12.SMILE.flac
/home/p0l1t1c1an/Music/Persona_4/13.Backside_Of_The_TV.flac
/home/p0l1t1c1an/Music/Persona_4/14.Deduction.flac
/home/p0l1t1c1an/Music/Persona_4/15.Castle.flac
/home/p0l1t1c1an/Music/Persona_4/16.Border_of_Insanity.flac
/home/p0l1t1c1an/Music/Persona_4/17.I'll_Face_Myself_-Battle-.flac
/home/p0l1t1c1an/Music/Persona_4/18.I'll_Face_Myself.flac
/home/p0l1t1c1an/Music/Persona_4/19.muscle_blues.flac
/home/p0l1t1c1an/Music/Persona_4/20.It's_SHOW_TIME!.flac
/home/p0l1t1c1an/Music/Persona_4/21.Someone_else's_man.flac
/home/p0l1t1c1an/Music/Persona_4/22.Quelorie_MAGIC!.flac
/home/p0l1t1c1an/Music/Persona_4/23.Sauna.flac
/home/p0l1t1c1an/Music/Persona_4/24.Awakening.flac
/home/p0l1t1c1an/Music/Persona_4/25.Reach_Out_To_The_Truth.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/01.Gone_Hollywood.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/02.The_Logical_Song.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/03.Goodbye_Stranger.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/04.Breakfast_in_America.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/05.Oh_Darling.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/06.Take_the_Long_Way_Home.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/07.Lord_Is_It_Mine.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/08.Just_Another_Nervous_Wreck.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/09.Casual_Conversations.flac
/home/p0l1t1c1an/Music/Supertramp/Breakfast_in_America/10.Child_of_Vision.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/1.Give_a_Little_Bit.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/2.Lover_Boy.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/3.Even_in_the_Quietest_Moments.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/4.Downstream.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/5.Babaji.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/6.From_Now_On.flac
/home/p0l1t1c1an/Music/Supertramp/Even_in_the_Quietest_Moments/7.Fools_Overture.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/1.School.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/2.Bloody_Well_Right.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/3.Hide_in_Your_Shell.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/4.Asylum.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/5.Dreamer.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/6.Rudy.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/7.If_Everyone_Was_Listening.flac
/home/p0l1t1c1an/Music/Supertramp/Crime_of_the_Century/8.Crime_of_the_Century.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/01.Drive_My_Car.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/02.Norwegian_Wood.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/03.You_Wont_See_Me.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/04.Nowhere_Man.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/05.Think_for_Yourself.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/06.The_Word.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/07.Michelle.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/08.What_Goes_On.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/09.Girl.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/10.Im_Looking_Through_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/11.In_My_Life.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/12.Wait.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/13.If_I_Needed_Someone.flac
/home/p0l1t1c1an/Music/The_Beatles/Rubber_Soul/14.Run_for_Your_Life.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/01.Back_in_the_USSR.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/02.Dear_Prudence.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/03.Glass_Onion.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/04.Ob_La_Di_Ob_La_Da.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/05.Wild_Honey_Pie.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/06.The_Continuing_Story_of_Bungalow_Bill.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/07.While_My_Guitar_Gently_Weeps.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/08.Happiness_Is_a_Warm_Gun.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/09.Martha_My_Dear.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/10.Im_So_Tired.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/11.Blackbird.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/12.Piggies.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/13.Rocky_Raccoon.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/14.Dont_Pass_Me_By.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/15.Why_Dont_We_Do_It_in_the_Road.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/16.I_Will.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/17.Julia.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/18.Birthday.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/19.Yer_Blues.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/20.Mother_Natures_Son.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/21.Everybodys_Got_Something_to_Hide_Except_Me_and_My_Monkey.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/22.Sexy_Sadie.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/23.Helter_Skelter.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/24.Long_Long_Long.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/25.Revolution_1.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/26.Honey_Pie.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/27.Savoy_Truffle.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/28.Cry_Baby_Cry.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/29.Revolution_9.flac
/home/p0l1t1c1an/Music/The_Beatles/White_Album/30.Good_Night.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/01.Get_Back.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/02.Dig_a_Pony.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/03.For_You_Blue.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/04.The_Long_and_Winding_Road.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/05.Two_of_Us.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/06.Ive_Got_a_Feeling.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/07.One_After_909.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/08.Dont_Let_Me_Down.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/09.I_Me_Mine.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/10.Across_the_Universe.flac
/home/p0l1t1c1an/Music/The_Beatles/Let_It_Be_Naked/11.Let_It_Be.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/01.Help.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/02.The_Night_Before.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/03.Youve_Got_to_Hide_Your_Love_Away.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/04.I_Need_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/05.Another_Girl.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/06.Youre_Going_to_Lose_That_Girl.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/07.Ticket_to_Ride.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/08.Act_Naturally.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/09.Its_Only_Love.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/10.You_Like_Me_Too_Much.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/11.Tell_Me_What_You_See.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/12.Ive_Just_Seen_a_Face.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/13.Yesterday.flac
/home/p0l1t1c1an/Music/The_Beatles/Help/14.Dizzy_Miss_Lizzy.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/01.Magical_Mystery_Tour.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/02.The_Fool_on_the_Hill.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/03.Flying.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/04.Blue_Jay_Way.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/05.Your_Mother_Should_Know.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/06.I_Am_the_Walrus.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/07.Hello_Goodbye.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/08.Strawberry_Fields_Forever.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/09.Penny_Lane.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/10.Baby_Youre_a_Rich_Man.flac
/home/p0l1t1c1an/Music/The_Beatles/Magical_Mystery_Tour/11.All_You_Need_Is_Love.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/01.I_Saw_Her_Standing_There.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/02.Misery.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/03.Anna_Go_to_Him.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/04.Chains.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/05.Boys.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/06.Ask_Me_Why.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/07.Please_Please_Me.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/08.Love_Me_Do.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/09.PS_I_Love_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/10.Baby_Its_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/11.Do_You_Want_to_Know_a_Secret.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/12.A_Taste_of_Honey.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/13.Theres_a_Place.flac
/home/p0l1t1c1an/Music/The_Beatles/Please_Please_Me/14.Twist_and_Shout.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/01.Taxman.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/02.Eleanor_Rigby.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/03.Im_Only_Sleeping.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/04.Love_You_To.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/05.Here_There_and_Everywhere.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/06.Yellow_Submarine.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/07.She_Said_She_Said.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/08.Good_Day_Sunshine.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/09.And_Your_Bird_Can_Sing.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/10.For_No_One.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/11.Doctor_Robert.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/12.I_Want_to_Tell_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/13.Got_to_Get_You_Into_My_Life.flac
/home/p0l1t1c1an/Music/The_Beatles/Revolver/14.Tomorrow_Never_Knows.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/01.No_Reply.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/02.I’m_a_Loser.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/03.Baby’s_in_Black.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/04.Rock_and_Roll_Music.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/05.I’ll_Follow_the_Sun.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/06.Mr._Moonlight.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/07.Kansas_City__Hey‐Hey‐Hey‐Hey!.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/08.Eight_Days_a_Week.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/09.Words_of_Love.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/10.Honey_Don’t.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/11.Every_Little_Thing.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/12.I_Don’t_Want_to_Spoil_the_Party.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/13.What_You’re_Doing.flac
/home/p0l1t1c1an/Music/The_Beatles/Beatles_For_Sale/14.Everybody’s_Trying_to_Be_My_Baby.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/01.A_Hard_Days_Night_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/02.Tell_Me_Why_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/03.Ill_Cry_Instead_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/04.I_Should_Have_Known_Better_instrumental_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/05.Im_Happy_Just_to_Dance_With_You_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/06.And_I_Love_Her_instrumental_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/07.I_Should_Have_Known_Better_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/08.If_I_Fell_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/09.And_I_Love_Her_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/10.Ringos_Theme_This_Boy_instrumental_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/11.Cant_Buy_Me_Love_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/12.A_Hard_Days_Night_instrumental_mono.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/13.A_Hard_Days_Night_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/14.Tell_Me_Why_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/15.Ill_Cry_Instead_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/16.I_Should_Have_Known_Better_instrumental_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/17.Im_Happy_Just_to_Dance_With_You_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/18.And_I_Love_Her_instrumental_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/19.I_Should_Have_Known_Better_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/20.If_I_Fell_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/21.And_I_Love_Her_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/22.Ringos_Theme_This_Boy_instrumental_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/23.Cant_Buy_Me_Love_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Hard_Days_Night/24.A_Hard_Days_Night_instrumental_stereo.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/01.Sgt._Peppers_Lonely_Hearts_Club_Band.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/02.With_a_Little_Help_From_My_Friends.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/03.Lucy_in_the_Sky_With_Diamonds.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/04.Getting_Better.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/05.Fixing_a_Hole.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/06.Shes_Leaving_Home.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/07.Being_for_the_Benefit_of_Mr._Kite!.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/08.Within_You_Without_You.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/09.When_Im_Sixty_Four.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/10.Lovely_Rita.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/11.Good_Morning_Good_Morning.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/12.Sgt._Peppers_Lonely_Hearts_Club_Band_reprise.flac
/home/p0l1t1c1an/Music/The_Beatles/Sgt_Peppers/13.A_Day_in_the_Life.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/01.Come_Together.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/02.Something.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/03.Maxwells_Silver_Hammer.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/04.Oh!_Darling.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/05.Octopuss_Garden.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/06.I_Want_You_Shes_So_Heavy.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/07.Here_Comes_the_Sun.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/08.Because.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/09.You_Never_Give_Me_Your_Money.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/10.Sun_King.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/11.Mean_Mr_Mustard.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/12.Polythene_Pam.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/13.She_Came_In_Through_the_Bathroom_Window.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/14.Golden_Slumbers.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/15.Carry_That_Weight.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/16.The_End.flac
/home/p0l1t1c1an/Music/The_Beatles/Abbey_Road/17.Her_Majesty.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/01.Just_What_I_Needed.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/02.Since_Youre_Gone.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/03.Lets_Go.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/04.You_Might_Think.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/05.Shake_It_Up.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/06.Drive.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/07.Tonight_She_Comes.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/08.My_Best_Friends_Girl.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/09.Dont_Tell_Me_No.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/10.Youre_All_Ive_Got_Tonight.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/11.Im_Not_the_One.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/12.Candy-O.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/13.Heartbeat_City.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/14.Touch_and_Go.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/15.Moving_in_Stereo.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/16.Dangerous_Type.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/17.Sad_Song.flac
/home/p0l1t1c1an/Music/The_Cars/Moving_in_Stereo/18.Everything_You_Say_live.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/01.Time_Is_on_My_Side.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/02.I_Cant_Get_No_Satisfaction.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/03.Get_Off_of_My_Cloud.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/04.19th_Nervous_Breakdown.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/05.Mothers_Little_Helper.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/06.Paint_It_Black.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/07.Under_My_Thumb.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/08.Ruby_Tuesday.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/09.Shes_a_Rainbow.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/10.Jumpin_Jack_Flash.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/11.Sympathy_for_the_Devil.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/12.Gimme_Shelter.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/13.You_Cant_Always_Get_What_You_Want.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/14.Honky_Tonk_Women.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/15.Brown_Sugar.flac
/home/p0l1t1c1an/Music/Rolling_Stones/The_Very_Best/16.Wild_Horses.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/01.I_Cant_Explain.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/02.Anyway_Anyhow_Anywhere.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/03.My_Generation.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/04.The_Kids_Are_Alright.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/05.A_Legal_Matter.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/06.Substitute.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/07.Im_a_Boy.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/08.Boris_the_Spider.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/09.Happy_Jack.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/10.Pictures_of_Lily.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/11.I_Can_See_for_Miles.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/12.Call_Me_Lightning.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/13.Magic_Bus.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/14.Pinball_Wizard.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/15.Im_Free.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/16.See_Me_Feel_Me.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/17.The_Seeker.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/18.Summertime_Blues.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/19.My_Wife.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/20.Baba_ORiley.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/21.Bargain.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/22.Behind_Blue_Eyes.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/23.Wont_Get_Fooled_Again.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/24.Lets_See_Action.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/25.Pure_and_Easy.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/26.Join_Together.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/27.Long_Live_Rock.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/28.The_Real_Me.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/29.515.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/30.Love_Reign_Oer_Me.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/31.Squeeze_Box.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/32.Who_Are_You.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/33.Sister_Disco.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/34.You_Better_You_Bet.flac
/home/p0l1t1c1an/Music/The_Who/Ultimate_Collection/35.Eminence_Front.flac
