#! /bin/sh

sxhkd &
unclutter &
picom &
redshift &
~/.fehbg &
$HOME/.config/polybar/launch.sh

xidle -no -program "$HOME/bin/blurlock" -timeout 300 &

xinput set-prop "Virtual core XTEST pointer" "Coordinate Transformation Matrix" .5 0 0 0 .5 0 0 0 1
xinput set-prop "/dev/wsmouse" "Coordinate Transformation Matrix" .5 0 0 0 .5 0 0 0 1
xinput set-prop "/dev/wsmouse0" "Coordinate Transformation Matrix" .5 0 0 0 .5 0 0 0 1

bspc monitor -d       

bspc config border_width        0
bspc config window_gap          6

bspc config pointer_modifier	control
bspc config pointer_action1 	move
bspc config pointer_action2	resize_side
bspc config pointer_action3	resize_corner

bspc config split_ratio         0.50
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config automatic_scheme	longest_side

bspc rule -a Firefox desktop='^3' state=fullscreen layer=below
bspc rule -a Gimp desktop='^4'
bspc rule -a Inkscape desktop='^5'
bspc rule -a Mines state=floating layer=above
bspc rule -a Pcmanfm state=floating layer=above

