if [ "$(tty)" = "/dev/ttyv0" ]; then
	startx
else
	# Lines configured by zsh-newuser-install
	HISTFILE=~/.histfile
	HISTSIZE=2000
	SAVEHIST=2000
	setopt nomatch
	unsetopt autocd beep extendedglob notify
	bindkey -v
	# End of lines configured by zsh-newuser-install
	# The following lines were added by compinstall
	zstyle :compinstall filename '/home/p0l1t1c1an/.zshrc'

	autoload -Uz compinit
	compinit
	# End of lines added by compinstall

	zstyle ':completion:*' menu select
	autoload -U colors && colors
	alias rm='rm -i' ls='ls --color=auto' :q='exit' vim='nvim'

	source ~/powerlevel10k/powerlevel10k.zsh-theme
	source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
	source ~/zsh-history-substring/zsh-history-substring-search.zsh

	ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets pattern cursor)

	bindkey '^[[A' history-substring-search-up
	bindkey '^[[B' history-substring-search-down

	# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
	[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

	neofetch
fi
